### ISSUE TITLE
Is FSR3 API the same as FSR2 API?

### ISSUE THREAD

**Issue by moaazassali** [GPUOpen-LibrariesAndSDKs/FidelityFX-SDK#21]
I am looking to mod FSR3 into a game by following a pre-existing DLSS -> FSR2 mod, and I am wondering if the FSR3 API is the same as that of FSR2. As in, would it be a simple swap of header files (using FSR3 files instead of FSR2) and then recompiling, or are there new parameters now?

**Comment by rys** [comment]
Due to the nature of how the overall technique works, the API isn't the same, and there's more work to do than just swapping to the new code and rebuilding. We've tried to keep it similar and familiar where possible to make integrations easier. Please take a look at the documentation for the frame interpolation, frame pacing and optical flow systems to get a feel for what's needed.

**Comment by ohmaya** [comment]
The APIs have an additional "Upscaler" have their number increased: ffxFsr3UpscalerContextDispatch
